server:
  port: 8080
  host: localhost
  servlet:
    encoding:
      charset: utf-8
      force: true
  datasource:
    url: ''
  jpa:
    hibernate:
      ddl-auto: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
